sqlglot_dialect: duckdb

opinions_config:
  ignore_opinions: None # No opinion is globally ignored

files:
  sql: ".*(models|macros|tests)/.*" # Exlcude sql files that don't match this regex
  #yaml:
  #md:
